### PR TITLE
It should be clearer that Put, Post, Delete are not supported

### PR DESCRIPTION
**Pull request by kenmazaika**
The current Readme implies that they do work except for a small TODO at the bottom of the file.

### CODE REVIEW

**Comment by moonmaster9000** [comment]
hi ken, put, post, delete ARE supported - the only thing that needs updating in the README is the TODO at the bottom.

**Comment by jingta** [comment]
it looks like they are only supported for xml....is it possible to support json as well?

**Comment by moonmaster9000** [comment]
i would _love_ a pull request that adds json support to Dupe. but unfortunately I don't have the time to do that at the moment.

**Comment by moonmaster9000** [comment]
by that i meant that I don't have the time to add in that functionality at the moment. but if you were to send me a pull request, i would love it!

**Pull request closed without merging**
